title: Bugzilla
email: developers@bugzilla.org
description: ""
baseurl: ""
url: ""

sass:
  sass_dir: _sass

paginate: 10
paginate_path: "/blog/page/:num/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Bugzilla Team
      breadcrumbs:
      - name: Blog
        link: /blog/
      permalink: /blog/:year/:month/:day/:title/
      ogtype: article

markdown: kramdown
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
