# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Jekyll configuration

title: "Bugzilla"
email: "developers@bugzilla.org"
description: "Jekyll theme for Bugzilla websites"
baseurl: ""
url: "https://bugzilla.org"

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
