title: "Bugzilla"
email: "developers@bugzilla.org"
description: "Jekyll theme for Bugzilla websites"
baseurl: ""
url: "https://bugzilla.org"

sass:
  sass_dir: _sass

markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
